# Site settings
title: Kaitlin S. Boston, Ed.M.
email: ksboston05@gmail.com
description: Experienced elementary teacher, special education expert, literacy specialist, autism advocate
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.kaitlinboston.com" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
#500px_url:
facebook_url: https://www.facebook.com/kesanford
github_url: https://github.com/ksboston
#gitlab_url: https://gitlab.com/u/andrewbanchich
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
#instagram_url:
linkedin_url: https://www.linkedin.com/in/kaitlinboston/
#pinterest_url:
email_url: ksboston05@gmail.com
#twitter_url: https://twitter.com/kesanford

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

google_analytics: UA-134388315-1

